# services:
#   app:
#     image: debian:bullseye
#     # command: sh -c "yarn install && yarn run dev"
#     command: "docker buid -t mariadb:custom srcs/requirements/mariadb/ && run -d mariadb:custom"
#     ports:
#       # - 127.0.0.1:3000:3000
#       - localhost
#     working_dir: /mariadb
#     # volumes:
#     #   - ./:/app
#     environment:
#       # MYSQL_HOST: mysql
#       # MYSQL_USER: root
#       # MYSQL_PASSWORD: secret
#       # MYSQL_DB: todos


version: "3.8"

services:
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    volumes:
      - vwp:/var/www/html
    networks:
      - incepnet
    image: wordpress:custom
    restart: always
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    networks:
      - incepnet
    image: nginx:custom
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
    volumes:
      - vdb:/var/lib/mysql
    networks:
      - incepnet
    image: mariadb:custom
    restart: always

volumes:
  vdb:
    driver_opts:
      type: none
      device: /Users/charline/cdutel-l/data/mariadbData
      o: bind
  vwp:
    driver_opts:
      type: none
      device: /Users/charline/cdutel-l/data/wordpress
      o: bind

networks:
  incepnet:
    driver: bridge


      