version: "3.8"

services:
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    volumes:
      - vwp:/var/www/html
    networks:
      - incepnet
    image: wordpress:custom
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    environment:
      - DB_NAME=${DB_NAME}
      - USER_NAME=${USER_NAME}
      - ROOT_MDP=${ROOT_MDP}
      - USER_MDP=${USER_MDP}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_MDP=${WP_ADMIN_MDP}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER_NAME=${WP_USER_NAME}
      - WP_USER_MDP=${WP_USER_MDP}
      - WP_USER_MAIL=${WP_USER_MAIL}

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    networks:
      - incepnet
    image: nginx:custom
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    volumes:
      - vwp:/var/www/html

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - USER_NAME=${USER_NAME}
        - ROOT_MDP=${ROOT_MDP}
        - USER_MDP=${USER_MDP}
    volumes:
      - vdb:/var/lib/mysql
    networks:
      - incepnet
    image: mariadb:custom
    restart: always
    env_file: .env

volumes:
  vdb:
    driver_opts:
      type: none
      device: /home/cdutel-l/data/mariadbData
      o: bind
  vwp:
    driver_opts:
      type: none
      device: /home/cdutel-l/data/wordpressData
      o: bind

networks:
  incepnet:
    driver: bridge

      